#define TAG_SYSTEM
#define GAMEPLAYS_SYSTEM
// #define TURNAMENT_SYSTEM
// #define STATS_SYSTEM
#define SKIN_SYSTEM

#define NEWBIE_LEVEL_BONUS          2

/* Gameplays System Settings */

#define SECOUNDS_TO_CHOOSE          15.0     // cate secunde asteptam pentru vot
#define SECOUNDS_WAITING_PLAYERS    15.0     // cate secunde asteptam pentru a se conecta jucatorii

/* End Gameplays System Settings */
